from app.models.user import User
from app.models.department import Department
from app.models.complaint_category import ComplaintCategory
from app.models.complaint_priority import ComplaintPriority
from app.models.complaint_status import ComplaintStatus
from app.models.complaint import Complaint
from app.models.complaint_image import ComplaintImage
from app.models.complaint_history import ComplaintHistory
from app.models.complaint_support import ComplaintSupport
from app.models.officer_remark import OfficerRemark
from app.models.notification import Notification