"""add citizen confirmation fields

Revision ID: 046fdf3ec000
Revises: 58e7436d4819
Create Date: 2026-07-17 15:13:46.321712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '046fdf3ec000'
down_revision: Union[str, Sequence[str], None] = '58e7436d4819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('citizen_feedback', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('citizen_rating', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('closed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'closed_at')
    op.drop_column('complaints', 'citizen_rating')
    op.drop_column('complaints', 'citizen_feedback')
    # ### end Alembic commands ###
