"""create complaint categories table

Revision ID: 0baba4c3a85b
Revises: 90bb29c29381
Create Date: 2026-07-15 11:09:55.097386

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0baba4c3a85b'
down_revision: Union[str, Sequence[str], None] = '90bb29c29381'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_categories',
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_complaint_categories_id'), 'complaint_categories', ['id'], unique=False)
    op.create_index(op.f('ix_complaint_categories_name'), 'complaint_categories', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_categories_name'), table_name='complaint_categories')
    op.drop_index(op.f('ix_complaint_categories_id'), table_name='complaint_categories')
    op.drop_table('complaint_categories')
    # ### end Alembic commands ###
