"""create complaint statuses table

Revision ID: 0c072e30da10
Revises: 80a9809e2315
Create Date: 2026-07-15 11:48:01.599496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c072e30da10'
down_revision: Union[str, Sequence[str], None] = '80a9809e2315'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_statuses',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('is_final', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sequence')
    )
    op.create_index(op.f('ix_complaint_statuses_id'), 'complaint_statuses', ['id'], unique=False)
    op.create_index(op.f('ix_complaint_statuses_name'), 'complaint_statuses', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_statuses_name'), table_name='complaint_statuses')
    op.drop_index(op.f('ix_complaint_statuses_id'), table_name='complaint_statuses')
    op.drop_table('complaint_statuses')
    # ### end Alembic commands ###
