"""add complaint lock fields

Revision ID: 1fcb75cc05fa
Revises: 046fdf3ec000
Create Date: 2026-07-17 19:55:30.783044

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1fcb75cc05fa'
down_revision: Union[str, Sequence[str], None] = '046fdf3ec000'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('resolution_duration_hours', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('is_locked', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'is_locked')
    op.drop_column('complaints', 'resolution_duration_hours')
    # ### end Alembic commands ###
