"""update complaint history

Revision ID: 43c983e3bb4c
Revises: acc65f1d30e9
Create Date: 2026-07-17 08:48:47.113674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '43c983e3bb4c'
down_revision: Union[str, Sequence[str], None] = 'acc65f1d30e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint_history', sa.Column('old_status_id', sa.Integer(), nullable=False))
    op.add_column('complaint_history', sa.Column('new_status_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('complaint_history_ibfk_3'), 'complaint_history', type_='foreignkey')
    op.create_foreign_key(None, 'complaint_history', 'complaint_statuses', ['new_status_id'], ['id'])
    op.create_foreign_key(None, 'complaint_history', 'complaint_statuses', ['old_status_id'], ['id'])
    op.drop_column('complaint_history', 'status_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint_history', sa.Column('status_id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'complaint_history', type_='foreignkey')
    op.drop_constraint(None, 'complaint_history', type_='foreignkey')
    op.create_foreign_key(op.f('complaint_history_ibfk_3'), 'complaint_history', 'complaint_statuses', ['status_id'], ['id'])
    op.drop_column('complaint_history', 'new_status_id')
    op.drop_column('complaint_history', 'old_status_id')
    # ### end Alembic commands ###
