"""add resolution fields

Revision ID: 58e7436d4819
Revises: da8534f5542f
Create Date: 2026-07-17 14:45:27.769875

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '58e7436d4819'
down_revision: Union[str, Sequence[str], None] = 'da8534f5542f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('resolution_remarks', sa.Text(), nullable=True))
    op.add_column('complaints', sa.Column('resolution_image_url', sa.String(length=500), nullable=True))
    op.add_column('complaints', sa.Column('resolved_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'resolved_at')
    op.drop_column('complaints', 'resolution_image_url')
    op.drop_column('complaints', 'resolution_remarks')
    # ### end Alembic commands ###
