"""add indexes to complaint foreign keys

Revision ID: 7e5a5131a230
Revises: 1fcb75cc05fa
Create Date: 2026-07-19 14:34:25.256868

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7e5a5131a230'
down_revision: Union[str, Sequence[str], None] = '1fcb75cc05fa'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_complaints_assigned_officer_id'), 'complaints', ['assigned_officer_id'], unique=False)
    op.create_index(op.f('ix_complaints_category_id'), 'complaints', ['category_id'], unique=False)
    op.create_index(op.f('ix_complaints_citizen_id'), 'complaints', ['citizen_id'], unique=False)
    op.create_index(op.f('ix_complaints_department_id'), 'complaints', ['department_id'], unique=False)
    op.create_index(op.f('ix_complaints_priority_id'), 'complaints', ['priority_id'], unique=False)
    op.create_index(op.f('ix_complaints_status_id'), 'complaints', ['status_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaints_status_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_priority_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_department_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_citizen_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_category_id'), table_name='complaints')
    op.drop_index(op.f('ix_complaints_assigned_officer_id'), table_name='complaints')
    # ### end Alembic commands ###
