"""create complaint priorities table

Revision ID: 80a9809e2315
Revises: 0baba4c3a85b
Create Date: 2026-07-15 11:30:51.618024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '80a9809e2315'
down_revision: Union[str, Sequence[str], None] = '0baba4c3a85b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('complaint_priorities',
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=False),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level')
    )
    op.create_index(op.f('ix_complaint_priorities_id'), 'complaint_priorities', ['id'], unique=False)
    op.create_index(op.f('ix_complaint_priorities_name'), 'complaint_priorities', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_complaint_priorities_name'), table_name='complaint_priorities')
    op.drop_index(op.f('ix_complaint_priorities_id'), table_name='complaint_priorities')
    op.drop_table('complaint_priorities')
    # ### end Alembic commands ###
