"""update complaint ai fields

Revision ID: 88a723983d25
Revises: 223d17e0779d
Create Date: 2026-07-16 14:03:06.383319

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '88a723983d25'
down_revision: Union[str, Sequence[str], None] = '223d17e0779d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('ai_category_id', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('ai_department_id', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('ai_priority_id', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('ai_confidence', sa.Float(), nullable=True))
    op.add_column('complaints', sa.Column('final_category_id', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('final_department_id', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('final_priority_id', sa.Integer(), nullable=True))
    op.add_column('complaints', sa.Column('final_description', sa.Text(), nullable=True))
    op.create_foreign_key(None, 'complaints', 'complaint_categories', ['final_category_id'], ['id'])
    op.create_foreign_key(None, 'complaints', 'departments', ['final_department_id'], ['id'])
    op.create_foreign_key(None, 'complaints', 'complaint_priorities', ['ai_priority_id'], ['id'])
    op.create_foreign_key(None, 'complaints', 'departments', ['ai_department_id'], ['id'])
    op.create_foreign_key(None, 'complaints', 'complaint_priorities', ['final_priority_id'], ['id'])
    op.create_foreign_key(None, 'complaints', 'complaint_categories', ['ai_category_id'], ['id'])
    op.drop_column('complaints', 'ai_category')
    op.drop_column('complaints', 'ai_priority')
    op.drop_column('complaints', 'ai_department')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('ai_department', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('complaints', sa.Column('ai_priority', mysql.VARCHAR(length=100), nullable=True))
    op.add_column('complaints', sa.Column('ai_category', mysql.VARCHAR(length=100), nullable=True))
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'final_description')
    op.drop_column('complaints', 'final_priority_id')
    op.drop_column('complaints', 'final_department_id')
    op.drop_column('complaints', 'final_category_id')
    op.drop_column('complaints', 'ai_confidence')
    op.drop_column('complaints', 'ai_priority_id')
    op.drop_column('complaints', 'ai_department_id')
    op.drop_column('complaints', 'ai_category_id')
    # ### end Alembic commands ###
