"""add image_url to complaints

Revision ID: 8d2c5bcaef80
Revises: c27bd4868998
Create Date: 2026-07-24 17:59:08.147197

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8d2c5bcaef80'
down_revision: Union[str, Sequence[str], None] = 'c27bd4868998'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('image_url', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'image_url')
    # ### end Alembic commands ###
