"""add assigned officer id to complaints

Revision ID: acc65f1d30e9
Revises: 88a723983d25
Create Date: 2026-07-16 23:26:09.533483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'acc65f1d30e9'
down_revision: Union[str, Sequence[str], None] = '88a723983d25'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('assigned_officer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'complaints', 'users', ['assigned_officer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'complaints', type_='foreignkey')
    op.drop_column('complaints', 'assigned_officer_id')
    # ### end Alembic commands ###
