"""add offline image sync fields

Revision ID: c27bd4868998
Revises: d8a26769b80e
Create Date: 2026-07-24 11:21:20.820655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c27bd4868998'
down_revision: Union[str, Sequence[str], None] = 'd8a26769b80e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaint_images', sa.Column('local_path', sa.String(length=500), nullable=True))
    op.add_column('complaint_images', sa.Column('storage_type', sa.String(length=20), nullable=False))
    op.add_column('complaint_images', sa.Column('is_synced', sa.Boolean(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaint_images', 'is_synced')
    op.drop_column('complaint_images', 'storage_type')
    op.drop_column('complaint_images', 'local_path')
    # ### end Alembic commands ###
