"""add rejection_reason

Revision ID: cedf2667b0c8
Revises: 43c983e3bb4c
Create Date: 2026-07-17 09:14:07.618148

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cedf2667b0c8'
down_revision: Union[str, Sequence[str], None] = '43c983e3bb4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('rejection_reason', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'rejection_reason')
    # ### end Alembic commands ###
