"""add started_at to complaints

Revision ID: f3b81a77cfc4
Revises: cedf2667b0c8
Create Date: 2026-07-17 11:11:09.145174

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3b81a77cfc4'
down_revision: Union[str, Sequence[str], None] = 'cedf2667b0c8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('complaints', sa.Column('started_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('complaints', 'started_at')
    # ### end Alembic commands ###
